sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t meg/docker-frontend .
  
script:
  - docker run -e CI=true meg/docker-frontend npm run test 
